In [ ]:
import pandas as pd
import numpy as np

In [14]:
pd.Series ([1, 2, 'hi',np.nan])

0      1
1      2
2     hi
3    NaN
dtype: object

In [15]:
dates = pd.date_range("20210101",periods=6)
dates

DatetimeIndex(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
               '2021-01-05', '2021-01-06'],
              dtype='datetime64[us]', freq='D')

In [16]:
np.random.randn(6, 4)

array([[-0.50364885, -2.05128839,  0.38067643,  1.57876112],
       [-1.25196226,  0.71986289, -0.0185141 , -0.34359951],
       [ 1.11807638,  0.48238667, -0.36850743, -0.05603597],
       [-1.33339239,  2.13127843, -2.27309995, -1.72727487],
       [-0.46119016, -0.25089386, -0.48110353,  0.91434553],
       [ 0.66689509, -1.30889399, -1.02092968, -1.04291277]])

In [18]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates)
df

                   0         1         2         3
2021-01-01 -1.089863 -0.532834  0.844276 -0.913036
2021-01-02 -0.858042 -0.955681  1.354313 -0.628848
2021-01-03  0.022300 -1.187096  1.014512  0.052904
2021-01-04 -0.838632  1.429658 -1.297954  0.996663
2021-01-05  1.312732 -0.182873 -1.459743  0.192640
2021-01-06 -1.555470  0.994809  2.745707 -0.615059

In [19]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=['A','B','C','D'])
df

                   A         B         C         D
2021-01-01 -0.208446  0.161512 -1.177758 -0.874382
2021-01-02 -0.693396  0.376779  2.119070 -0.638425
2021-01-03 -0.208013  0.738647 -0.669195 -1.024682
2021-01-04 -0.317784 -1.091239  0.318533 -0.279221
2021-01-05  1.006951 -0.503513  0.662431  0.002639
2021-01-06  0.620153  0.197377 -2.117733 -1.363742

In [20]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.033244 -0.020073 -0.144109 -0.696302
std    0.641937  0.662498  1.498390  0.500169
min   -0.693396 -1.091239 -2.117733 -1.363742
25%   -0.290449 -0.337257 -1.050617 -0.987107
50%   -0.208229  0.179444 -0.175331 -0.756404
75%    0.413112  0.331928  0.576457 -0.369022
max    1.006951  0.738647  2.119070  0.002639

In [21]:
df.T

   2021-01-01  2021-01-02  2021-01-03  2021-01-04  2021-01-05  2021-01-06
A   -0.208446   -0.693396   -0.208013   -0.317784    1.006951    0.620153
B    0.161512    0.376779    0.738647   -1.091239   -0.503513    0.197377
C   -1.177758    2.119070   -0.669195    0.318533    0.662431   -2.117733
D   -0.874382   -0.638425   -1.024682   -0.279221    0.002639   -1.363742

In [23]:
df.to_csv(r"C:\Users\farzam\Desktop\mycsv.csv", index=False)